In [ ]:
from IPython.display import IFrame, YouTubeVideo
YouTubeVideo('iGFdh6_FePU',width=600, height=400)

In [ ]:
from google.colab import drive
drive.mount ('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [ ]:
import os 
os.chdir('/gdrive/My Drive/')

![Iris Flower Classes](https://drive.google.com//uc?id=15Qfdh2FxirWBtHtCvmmJOLcxhbnVfH2w) 

In [ ]:
import pandas as pd # manipulate your data
D = pd.read_csv("Iris.csv", index_col=0)
print(f"Data has {D.shape[0]} rows and {D.shape[1]} columns.\n")
D.head()

Data has 150 rows and 5 columns.



SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
print(type(D)) #DataFrame is a two-dimensional, labeled data structure with columns that can be of different data types.

<class 'pandas.core.frame.DataFrame'>


In [ ]:
D.Species.head()#head() prints only the first five rows

Id
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
5    Iris-setosa
Name: Species, dtype: object

In [ ]:
print(type(D.Species))#Each column of a DataFrame is of type Series: one-dimensional, labeled arrays with any data type and its index
#Each Series has one type of data.

<class 'pandas.core.series.Series'>


In [ ]:
# Use dot notation to access the Species column
D.Species

# Use .loc to get all rows using ":", for column Species
D.loc[:,"Species"]

# Use bracket notation to get the Species column
D["Species"]

print(D.Species.equals(D.loc[:,"Species"]))
print(D.Species.equals(D["Species"]))

True
True


In [ ]:
D1=D[D.SepalLengthCm <= 5.]

In [ ]:
print(f"Data has {D1.shape[0]} rows and {D1.shape[1]} columns.\n")
D1.head()

Data has 32 rows and 5 columns.



SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa
7             4.6           3.4            1.4           0.3  Iris-setosa

In [ ]:
D2=D[ (D.SepalLengthCm <= 5.) & (D.PetalLengthCm <= 1.)]


In [ ]:
print(f"Data has {D2.shape[0]} rows and {D2.shape[1]} columns.\n")
D2.head()

Data has 1 rows and 5 columns.



SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
23            4.6           3.6            1.0           0.2  Iris-setosa

In [ ]:
# len(): number of rows
print(f"len: {len(D[(D.SepalLengthCm <= 5.)])}")

# shape: tuple of (rows, cols)
print(f"shape: {D[(D.SepalLengthCm <= 5.)].shape}")

# size: number of elements in the df= rows*cols
print(f"size: {D[(D.SepalLengthCm <= 5.)].size}")

len: 32
shape: (32, 5)
size: 160


In [ ]:
print(f"{len(D.Species)}")
print(f"{D.Species.shape}")
print(f"{D.Species.size}")

150
(150,)
150


In [ ]:
D.loc[2,'Species']

'Iris-setosa'

In [ ]:
D.loc[2, 'Species'] = 'Iris-virginica'
D.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                          
1             5.1           3.5            1.4           0.2     Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-virginica
3             4.7           3.2            1.3           0.2     Iris-setosa
4             4.6           3.1            1.5           0.2     Iris-setosa
5             5.0           3.6            1.4           0.2     Iris-setosa

In [ ]:
D.loc[:, 'Species'] = 'Iris-virginica'
D.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                          
1             5.1           3.5            1.4           0.2  Iris-virginica
2             4.9           3.0            1.4           0.2  Iris-virginica
3             4.7           3.2            1.3           0.2  Iris-virginica
4             4.6           3.1            1.5           0.2  Iris-virginica
5             5.0           3.6            1.4           0.2  Iris-virginica

In [ ]:
D.loc[3:8,:]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                          
3             4.7           3.2            1.3           0.2  Iris-virginica
4             4.6           3.1            1.5           0.2  Iris-virginica
5             5.0           3.6            1.4           0.2  Iris-virginica
6             5.4           3.9            1.7           0.4  Iris-virginica
7             4.6           3.4            1.4           0.3  Iris-virginica
8             5.0           3.4            1.5           0.2  Iris-virginica

In [ ]:
D = pd.read_csv("Iris.csv", index_col=0)
pd.unique(D.Species)


array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
D.columns.tolist()

['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

In [ ]:
D_new=D.rename(columns={'SepalLengthCm': 'SepalLength', 'SepalWidthCm': 'SepalWidth','PetalLengthCm':'PetalLength', 'PetalWidthCm':'PetalWidth'})
D_new.replace({'Iris-setosa': 'setosa', 'Iris-versicolor': 'versicolor', 'Iris-virginica': 'virginica'},inplace=True)
 
D_new.head()
#D_new.to_csv('Iris_data.csv')
#D_new.to_csv('Iris_data_without_index.csv',index=False)

SepalLength  SepalWidth  PetalLength  PetalWidth Species
Id                                                          
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa

In [ ]:
D_new2=D_new.drop(columns = 'SepalLength')
D_new2.tail()

SepalWidth  PetalLength  PetalWidth    Species
Id                                                 
146         3.0          5.2         2.3  virginica
147         2.5          5.0         1.9  virginica
148         3.0          5.2         2.0  virginica
149         3.4          5.4         2.3  virginica
150         3.0          5.1         1.8  virginica

In [ ]:
import numpy as np #mathematical and scientific operations
D_new3=D_new.copy()
D_new3['weight']=np.nan
#D_new3.loc[3,:]='nan'
D_new3.head()

SepalLength  SepalWidth  PetalLength  PetalWidth Species  weight
Id                                                                  
1           5.1         3.5          1.4         0.2  setosa     NaN
2           4.9         3.0          1.4         0.2  setosa     NaN
3           4.7         3.2          1.3         0.2  setosa     NaN
4           4.6         3.1          1.5         0.2  setosa     NaN
5           5.0         3.6          1.4         0.2  setosa     NaN

In [ ]:
D_new4=D_new3.copy()
D5=D_new4.sort_values(by = ['SepalLength'],ascending=True) 

D5.head()


SepalLength  SepalWidth  PetalLength  PetalWidth Species  weight
Id                                                                  
14          4.3         3.0          1.1         0.1  setosa     NaN
43          4.4         3.2          1.3         0.2  setosa     NaN
39          4.4         3.0          1.3         0.2  setosa     NaN
9           4.4         2.9          1.4         0.2  setosa     NaN
42          4.5         2.3          1.3         0.3  setosa     NaN

In [ ]:
D5.dropna(axis=1)# to delete missing entries

SepalLength  SepalWidth  PetalLength  PetalWidth    Species
Id                                                              
14           4.3         3.0          1.1         0.1     setosa
43           4.4         3.2          1.3         0.2     setosa
39           4.4         3.0          1.3         0.2     setosa
9            4.4         2.9          1.4         0.2     setosa
42           4.5         2.3          1.3         0.3     setosa
..           ...         ...          ...         ...        ...
123          7.7         2.8          6.7         2.0  virginica
119          7.7         2.6          6.9         2.3  virginica
118          7.7         3.8          6.7         2.2  virginica
136          7.7         3.0          6.1         2.3  virginica
132          7.9         3.8          6.4         2.0  virginica

[150 rows x 5 columns]

In [ ]:
D_new.count()# axis=0 by default. 0: operation across columns, 1: operation across rows

NameError: ignored

In [ ]:
D_new.groupby(['Species']).mean() 

SepalLength  SepalWidth  PetalLength  PetalWidth
Species                                                     
setosa            5.006       3.418        1.464       0.244
versicolor        5.936       2.770        4.260       1.326
virginica         6.588       2.974        5.552       2.026

In [ ]:
D_new.groupby(['Species']).sum()

SepalLength  SepalWidth  PetalLength  PetalWidth
Species                                                     
setosa            250.3       170.9         73.2        12.2
versicolor        296.8       138.5        213.0        66.3
virginica         329.4       148.7        277.6       101.3

In [ ]:
D_new.groupby(['Species'])['SepalLength'].sum()

Species
setosa        250.3
versicolor    296.8
virginica     329.4
Name: SepalLength, dtype: float64

In [ ]:
D_new.count(axis=1)

Id
1      5
2      5
3      5
4      5
5      5
      ..
146    5
147    5
148    5
149    5
150    5
Length: 150, dtype: int64

In [ ]:
D_new.Species.value_counts()

virginica     50
versicolor    50
setosa        50
Name: Species, dtype: int64

In [ ]:
D_new.Species.value_counts()['virginica']

50

In [ ]:
D_new.head()

SepalLength  SepalWidth  PetalLength  PetalWidth Species
Id                                                          
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa

In [ ]:
D7=D_new.copy()
D7.Species = pd.Categorical(D7.Species)
D7.head()

SepalLength  SepalWidth  PetalLength  PetalWidth Species
Id                                                          
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa

In [ ]:
D7['Species'] = D7.Species.cat.codes
D7.tail()

SepalLength  SepalWidth  PetalLength  PetalWidth  Species
Id                                                            
146          6.7         3.0          5.2         2.3        2
147          6.3         2.5          5.0         1.9        2
148          6.5         3.0          5.2         2.0        2
149          6.2         3.4          5.4         2.3        2
150          5.9         3.0          5.1         1.8        2

In [ ]:
y = D7.Species
X=D7.drop('Species',axis=1)

In [ ]:
#sklearn: efficient tools for machine learning and statistical modeling
from sklearn.model_selection import train_test_split
import random
np.random.seed(10)
random.seed(1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [ ]:
from sklearn import neighbors
classifier=neighbors.KNeighborsClassifier()

In [ ]:
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
classifier.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [ ]:
predictions=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions))


0.9736842105263158


In [ ]:
classifier.score(X_test, y_test)#number of correct predictions divided by total predictions

0.9736842105263158

In [ ]:
prediction_probs = classifier.predict_proba(X_test)
print(prediction_probs)

[[0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.4 0.6]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.2 0.8]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  0.8 0.2]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  0.  1. ]]


In [ ]:
classifier.classes_

array([0, 1, 2], dtype=int8)

In [ ]:
from sklearn import tree
classifier=tree.DecisionTreeClassifier()
classifier.fit(X_train,y_train)
predictions=classifier.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,predictions))

0.9736842105263158


In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver='lbfgs')
lr.fit(X_train, y_train)
predictions = lr.predict(X_test)
lr.score(X_test, y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


1.0

In [ ]:
prediction_probs = lr.predict_proba(X_test)
print(np.round(prediction_probs,3))

[[0.004 0.884 0.112]
 [0.    0.163 0.837]
 [0.973 0.027 0.   ]
 [0.006 0.778 0.216]
 [0.975 0.025 0.   ]
 [0.063 0.924 0.013]
 [0.001 0.57  0.429]
 [0.021 0.945 0.034]
 [0.97  0.03  0.   ]
 [0.009 0.807 0.185]
 [0.01  0.716 0.274]
 [0.    0.18  0.82 ]
 [0.018 0.913 0.069]
 [0.967 0.033 0.   ]
 [0.981 0.019 0.   ]
 [0.    0.089 0.911]
 [0.012 0.737 0.252]
 [0.983 0.017 0.   ]
 [0.978 0.022 0.   ]
 [0.981 0.019 0.   ]
 [0.    0.04  0.96 ]
 [0.    0.041 0.959]
 [0.001 0.455 0.544]
 [0.947 0.053 0.   ]
 [0.018 0.863 0.12 ]
 [0.982 0.018 0.   ]
 [0.024 0.905 0.07 ]
 [0.011 0.85  0.14 ]
 [0.002 0.766 0.232]
 [0.    0.007 0.993]
 [0.004 0.861 0.135]
 [0.011 0.905 0.084]
 [0.    0.161 0.839]
 [0.    0.063 0.937]
 [0.    0.281 0.719]
 [0.98  0.02  0.   ]
 [0.    0.054 0.946]
 [0.    0.038 0.962]]


In [ ]:
params = {
    'solver': 'liblinear',
    'fit_intercept': False,
    'penalty': 'l1',
    'max_iter': 500
}
lr_modified = LogisticRegression(**params)
lr_modified.fit(X_train, y_train)
lr_modified.score(X_test, y_test)

0.9736842105263158

In [ ]:
thetas = lr.coef_
thetas

array([[-0.3679316 ,  0.89056797, -2.31031783, -1.00843776],
       [ 0.53105247, -0.35423763, -0.18480002, -0.6925378 ],
       [-0.16312087, -0.53633034,  2.49511785,  1.70097555]])

In [ ]:
# Print the name of the feature and the coefficient for each feature
for i in range(len(X.columns)):
    print("Feature {:<9s}: coefficient = {:<10f}".format(X.columns[i], thetas[0, i]))

Feature SepalLength: coefficient = -0.367932 
Feature SepalWidth: coefficient = 0.890568  
Feature PetalLength: coefficient = -2.310318 
Feature PetalWidth: coefficient = -1.008438 


In [ ]:
hyperparams = {
    'solver': ["liblinear"],
    'fit_intercept': [True, False],
    'penalty': ["l1", "l2"],
    'class_weight': [None, "balanced"]
}
# Get the values of hyperparams and convert them to a list of lists
hp_values = list(hyperparams.values())
hp_values


[['liblinear'], [True, False], ['l1', 'l2'], [None, 'balanced']]

In [ ]:
import itertools # helps with hyperparameter (grid) searching
# Get every combination of the hyperparameters
for hp in itertools.product(*hp_values):
    print(hp)

('liblinear', True, 'l1', None)
('liblinear', True, 'l1', 'balanced')
('liblinear', True, 'l2', None)
('liblinear', True, 'l2', 'balanced')
('liblinear', False, 'l1', None)
('liblinear', False, 'l1', 'balanced')
('liblinear', False, 'l2', None)
('liblinear', False, 'l2', 'balanced')


In [ ]:
# Loop through the combinations of hyperparams
for hp in itertools.product(*hp_values):

    # Create the model with the hyperparams
    estimator = LogisticRegression(solver=hp[0],
                                   fit_intercept=hp[1],
                                   penalty=hp[2],
                                   class_weight=hp[3])
    # Fit the model
    estimator.fit(X_train, y_train)
    print(f"Parameters used: {hp}")
    print(f"Mean accuracy of the model: {estimator.score(X_test, y_test)}\n")

Parameters used: ('liblinear', True, 'l1', None)
Mean accuracy of the model: 0.9736842105263158

Parameters used: ('liblinear', True, 'l1', 'balanced')
Mean accuracy of the model: 0.9736842105263158

Parameters used: ('liblinear', True, 'l2', None)
Mean accuracy of the model: 0.9473684210526315

Parameters used: ('liblinear', True, 'l2', 'balanced')
Mean accuracy of the model: 0.9473684210526315

Parameters used: ('liblinear', False, 'l1', None)
Mean accuracy of the model: 0.9736842105263158

Parameters used: ('liblinear', False, 'l1', 'balanced')
Mean accuracy of the model: 0.9473684210526315

Parameters used: ('liblinear', False, 'l2', None)
Mean accuracy of the model: 0.8947368421052632

Parameters used: ('liblinear', False, 'l2', 'balanced')
Mean accuracy of the model: 0.9473684210526315



In [ ]:
pd.get_dummies(D_new)# one-hot encoding

SepalLength  SepalWidth  ...  Species_versicolor  Species_virginica
Id                            ...                                       
1            5.1         3.5  ...                   0                  0
2            4.9         3.0  ...                   0                  0
3            4.7         3.2  ...                   0                  0
4            4.6         3.1  ...                   0                  0
5            5.0         3.6  ...                   0                  0
..           ...         ...  ...                 ...                ...
146          6.7         3.0  ...                   0                  1
147          6.3         2.5  ...                   0                  1
148          6.5         3.0  ...                   0                  1
149          6.2         3.4  ...                   0                  1
150          5.9         3.0  ...                   0                  1

[150 rows x 7 columns]

In [ ]:
from  sklearn import  datasets
iris=datasets.load_iris()

In [ ]:
x=iris.data
y=iris.target

In [ ]:
print(x.shape,y.shape)

(150, 4) (150,)


In [ ]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
